### PR TITLE
Do not erase error if callback is called sync

### LINKED ISSUE #17: Error are not passed from after to ready
I don't think this should happen.
Could be related to [this](https://github.com/mcollina/avvio/blob/master/boot.js#L177)?

Example:
```js
test('shold pass the errors from after to ready', (t) => {
  t.plan(6)

  const server = {}
  const app = boot(server, {})

  server.use(function (s, opts, done) {
    t.equal(s, server, 'the first argument is the server')
    t.deepEqual(opts, {}, 'no options')
    done()
  }).after((err, done) => {
    t.error(err)
    done(new Error('some error'))
  })

  server.onClose(() => {
    t.ok('onClose called')
  })

  server.ready(err => {
    t.is(err.message, 'some error') // this will fail
  })

  app.on('start', () => {
    server.close(() => {
      t.pass('booted')
    })
  })
})
```

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #17

### CODE REVIEW

File: boot.js [hunk 1]
```diff
@@ -207,16 +205,19 @@ function callWithCbOrNextTick (func, cb, context) {
     context = this._server
   }
 
+  var err = this._error
```
Comment (delvedor) [inline boot.js]: I think you should wrap this inside an `if (this)`, as was done few lines above :)
Or, if not needed, remove the `if (this)` few lines above :P

Comment (mcollina) [inline boot.js]: done
